// <auto-generated />
namespace BulletinSlideshow.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddProject : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddProject));
        
        string IMigrationMetadata.Id
        {
            get { return "201307150805164_AddProject"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
